export const fr = {
    services: [
        { title: 'Sites web professionnels', text: 'Une présence qui inspire confiance et transforme vos visiteurs en contacts.', detail: 'Site vitrine, présentation de vos services, formulaire de contact et référencement de base. Une expérience claire, rapide et adaptée à tous les écrans.' },
        { title: 'E-commerce', text: 'Une boutique intuitive pour présenter vos produits et faciliter l’achat.', detail: 'Catalogue, fiches produits, panier et parcours de commande. Les modes de livraison et de paiement sont définis avec vous selon votre activité.' },
        { title: 'Applications web', text: 'Des outils métier qui simplifient le quotidien de votre équipe.', detail: 'Gestion, tableaux de bord, espaces clients et plateformes internes. Nous partons de vos processus pour concevoir les fonctionnalités utiles.' },
        { title: 'UI/UX design', text: 'Des interfaces qui donnent envie. Des parcours qui font sens.', detail: 'Architecture de l’information, maquettes et prototypes interactifs. Chaque écran aide vos utilisateurs à trouver ce qu’ils cherchent.' },
        { title: 'IA & automatisation', text: 'Moins de tâches répétitives. Plus de temps pour votre activité.', detail: 'Analyse de documents, recherche intelligente et automatisation des échanges entre vos outils. Les usages sont choisis selon vos besoins et validés avec vous.' },
        { title: 'Maintenance & hébergement', text: 'Un site suivi dans la durée, pour avancer l’esprit tranquille.', detail: 'Gestion de l’hébergement, mises à jour, sauvegardes et certificats SSL. Le périmètre du support et les délais d’intervention sont précisés dans votre offre.' },
    ],
    projects: [
        { name: 'SmartRecruit AI', kind: 'recruit', category: 'PLATEFORME MÉTIER · INTELLIGENCE ARTIFICIELLE', headline: 'Faire se rencontrer compétences et opportunités.', problem: 'Comment identifier les compétences pertinentes dans un CV et les rapprocher des offres disponibles ?', solution: 'Une plateforme de recrutement qui analyse les compétences des CV et recommande des offres pertinentes. Elle aide à explorer les correspondances, tout en laissant la décision aux personnes.', tech: ['Next.js', 'TypeScript', 'FastAPI', 'PostgreSQL', 'Python', 'NLP'], features: ['Analyse des compétences', 'Recommandation d’offres', 'Parcours de recrutement'] },
        { name: 'SplitEasy', kind: 'split', category: 'APPLICATION WEB · FINANCE COLLABORATIVE', headline: 'Partager les dépenses. Garder la simplicité.', problem: 'Comment suivre les dépenses d’un groupe sans perdre de vue les soldes et les remboursements ?', solution: 'Un espace commun pour enregistrer les dépenses, consulter les soldes, suivre les règlements et échanger grâce au chat et aux notifications.', tech: [], features: ['Dépenses et remboursements', 'Analyses et soldes', 'Chat et notifications'] },
        { name: 'Finance Management', kind: 'finance', category: 'OUTIL DE GESTION · TABLEAU DE BORD', headline: 'Retrouver une vue claire de ses finances.', problem: 'Comment centraliser le suivi administratif et financier pour consulter les informations utiles ?', solution: 'Une solution de gestion réunissant les fonctionnalités de paiement et de reporting dans une interface de travail structurée.', tech: [], features: ['Suivi des paiements', 'Gestion administrative', 'Reporting financier'] },
    ],
    process: [
        { title: 'Découverte', text: 'Nous comprenons votre activité, vos besoins et vos objectifs.', detail: 'Nous échangeons sur vos clients, vos priorités et vos contraintes. Vous recevez une proposition avec un périmètre, un budget et un calendrier définis.', deliverable: 'Un brief clair et une proposition adaptée.' },
        { title: 'Design', text: 'Nous concevons une expérience moderne adaptée à votre marque.', detail: 'Nous structurons vos contenus, dessinons les parcours et préparons les maquettes. Vos retours permettent de valider la direction avant le développement.', deliverable: 'Des maquettes à valider ensemble.' },
        { title: 'Développement', text: 'Nous transformons le design en une solution rapide et fonctionnelle.', detail: 'Nous construisons votre solution et vérifions les parcours clés sur mobile et ordinateur. Vous suivez l’avancement et pouvez tester les fonctionnalités.', deliverable: 'Une version testable de votre solution.' },
        { title: 'Lancement & suivi', text: 'Mise en ligne, optimisation et accompagnement.', detail: 'Nous préparons la mise en ligne et la prise en main. Le support et la maintenance se poursuivent selon l’accompagnement choisi.', deliverable: 'Un lancement préparé et un suivi défini.' },
    ],
    projectTypes: ['Site vitrine', 'E-commerce', 'Application web', 'Refonte', 'Autre'],
    budgets: ['Moins de 2 000 MAD', '2 000 – 5 000 MAD', '5 000 – 10 000 MAD', '10 000+ MAD'],
};
