import Link from 'next/link';
import { ArabicBrand } from './arabic-brand';
import { LanguageSwitch } from './language-switch';
import { ArabicContact } from './arabic-contact';
import { ArabicProcess, ArabicBeforeAfter } from './arabic-interactions';
import { ArabicWebsitePortfolio } from './arabic-website-portfolio';
import { HeroDevices } from './hero-devices';
import { arabicServices } from '@/content/ar-services';
import { site, whatsappUrl } from '@/lib/site';

const extraServices = [
  ['تصميم تجربة المستخدم', 'واجهات واضحة ومسارات تساعد المستخدم على الوصول إلى ما يحتاجه.'],
  ['الذكاء الاصطناعي والأتمتة', 'ندرس المهام المتكررة ونحدد استخدامات عملية للأتمتة حسب احتياجاتك.'],
  ['الصيانة والاستضافة', 'متابعة وتحديثات وخيارات استضافة ودعم يحدد نطاقها في عرض المشروع.'],
];
export function ArabicHome() {
  return <>
    <header className="navbar"><div className="container arabic-nav"><a className="skip-link" href="#main">انتقل إلى المحتوى</a><Link href="/" aria-label="ShineoraTech — الرئيسية"><ArabicBrand /></Link><nav aria-label="التنقل الرئيسي">{[['الخدمات', '#services'], ['الأعمال', '#realisations'], ['من نحن', '#a-propos'], ['طريقة العمل', '#processus'], ['تواصل معنا', '#contact']].map(([label, href]) => <a href={href} key={href}>{label}</a>)}</nav><LanguageSwitch language="ar" /><a className="button small" href="#contact">اطلب عرض سعر</a></div></header>
    <main id="main">
      <section className="hero" id="accueil"><div className="hero-grid" aria-hidden="true" /><div className="container hero-layout"><div className="hero-copy"><p className="eyebrow">حلول رقمية للسعودية والكويت والخليج</p><h1>موقع يعبّر عنك.<br /><span>وتجربة تقرّب عملاءك.</span></h1><p className="hero-description">نصمم مواقع إلكترونية ومتاجر وتطبيقات ويب تناسب نشاطك، بهوية واضحة وتجربة عربية سلسة. نرافقك من الفكرة إلى الإطلاق، أينما كان مشروعك في الخليج.</p><div className="hero-actions"><a className="button" href="#contact">لنتحدث عن مشروعك</a><a className="button secondary" href="#realisations">استكشف أعمالنا</a></div><a className="hero-whatsapp" href={whatsappUrl('مرحباً ShineoraTech، أود مناقشة مشروعي الرقمي.')} target="_blank" rel="noopener noreferrer">تواصل مباشرة على واتساب ←</a></div><div className="hero-visual"><div className="visual-caption"><span>من الفكرة إلى تجربة متكاملة</span><span>01 / 04</span></div><HeroDevices language="ar" /><div className="visual-footnote">تصميم توضيحي · بيانات افتراضية</div></div></div><div className="container hero-bottom"><span>أفكار طموحة. حلول عملية.</span><span>مواقع / تصميم / تطبيقات</span></div></section>
      <div className="trust-bar"><div className="container trust-grid">{['تصميم عصري', 'تجربة تناسب جميع الأجهزة', 'حلول مخصصة', 'متابعة في كل مرحلة'].map(label => <div key={label}>✓ {label}</div>)}</div></div>
      <section className="section light" id="services"><div className="container"><div className="section-heading"><div><p className="eyebrow">01 / خدماتنا</p><h2>ما يحتاجه مشروعك<br />لينمو رقمياً.</h2></div><p className="section-intro">من موقع شركتك إلى أدوات عملك، نبني الحل حول احتياجاتك وأهدافك.</p></div><div className="services-grid">{Object.values(arabicServices).map((service, i) => <div key={service.slug}><article className="service-card"><div className="service-top"><span>0{i + 1}</span></div><h3>{service.label}</h3><p>{service.lead}</p><Link className="text-link service-page-link" href={`/${service.slug}/`}>تفاصيل الخدمة ←</Link></article></div>)}{extraServices.map(([heading, description], i) => <div key={heading}><article className="service-card"><div className="service-top"><span>0{i + 4}</span></div><h3>{heading}</h3><p>{description}</p><a className="text-link" href="#contact">ناقش احتياجاتك معنا ←</a></article></div>)}</div><div className="services-note"><span>لديك موقع وترغب في تطويره؟</span><Link href="/creation-site-web/">اكتشف خيارات إعادة التصميم</Link></div></div></section>
      <section className="section portfolio" id="realisations"><div className="container"><div className="section-heading"><div><p className="eyebrow">02 / معرض المواقع</p><h2>مواقع تستحق الاكتشاف.<br /><span className="muted-title">وتجارب متنوعة.</span></h2></div><p className="section-intro">استكشف المواقع حسب المجال وشاهد أمثلة لطريقة عرض الخدمات والمنتجات.</p></div><ArabicWebsitePortfolio /></div></section>
      <section className="section application-concepts" id="concepts-applications"><div className="container"><p className="eyebrow">مفاهيم / تطبيقات ويب</p><h2>أفكار لأدوات العمل اليومية.</h2><p className="section-intro">مفاهيم توضيحية للتوظيف والمصروفات والإدارة المالية.</p><div className="service-examples arabic-projects">{arabicServices['applications-web'].examples.map(example => <article className="arabic-concept" key={example.name}><h3><bdi>{example.name}</bdi></h3><p>{example.description}</p><Link href="/applications-web/" className="text-link">اكتشف تطوير التطبيقات ←</Link></article>)}</div><p className="portfolio-note">مفاهيم توضيحية فقط، دون بيانات حقيقية أو ادعاء نتائج عملاء.</p></div></section>
      <section className="section why" id="a-propos"><div className="container why-layout"><div><p className="eyebrow">03 / عن ShineoraTech</p><h2>تقنية تخدم فكرتك.<br /><span className="accent">ونشاطك هو نقطة البداية.</span></h2><p className="why-lead">نساعد الشركات ورواد الأعمال على بناء حضور رقمي واضح عبر مواقع ومتاجر وتطبيقات مخصصة. نفهم نشاطك أولاً، ثم نحدد معك الحل ومراحل العمل.</p><p className="audience">نستهدف المشاريع في السعودية والكويت والإمارات وقطر والبحرين وعُمان، عبر تعاون عن بُعد ومراحل تسليم واضحة.</p><a className="text-link" href="#contact">لنتعرف على مشروعك ←</a></div><div className="benefits">{[['هوية تناسبك', 'تصميم متناسق مع علامتك وخدماتك وجمهورك.'], ['وضوح على كل شاشة', 'تجربة عربية مريحة على الهاتف والكمبيوتر.'], ['اهتمام بالأداء', 'صور ومحتوى وتفاعلات نراجعها لتسهيل التصفح.'], ['نطاق عمل واضح', 'وظائف وميزانية ومسؤوليات نتفق عليها قبل التنفيذ.'], ['تواصل ومتابعة', 'مراجعات وشرح للاستخدام ودعم وفق العرض المتفق عليه.']].map(([heading, text]) => <div className="benefit" key={heading}><span>✓</span><div><h3>{heading}</h3><p>{text}</p></div></div>)}</div></div></section>
      <ArabicProcess />
      <ArabicBeforeAfter />
      <section className="cta-band"><div className="container cta-inner"><div><p className="eyebrow">المشروع القادم قد يكون مشروعك</p><h2>لديك فكرة؟<br />لنمنحها حضوراً.</h2></div><div><p>نحدد معك الخطوة المناسبة ونحوّل احتياجاتك إلى تجربة رقمية عملية.</p><a className="button ink-button" href="#contact">اطلب عرض سعر</a></div></div></section>
      <ArabicContact />
    </main>
    <footer className="footer"><div className="container"><div className="footer-grid"><div><Link href="/"><ArabicBrand /></Link><p>رؤيتك. وتقنيتنا.</p><span className="footer-location">نتعاون عن بُعد مع مشاريع في السعودية والكويت والخليج.</span></div><div><h3>استكشف</h3><a href="#services">الخدمات</a><a href="#realisations">الأعمال</a><a href="#a-propos">من نحن</a><a href="#contact">تواصل معنا</a></div><div><h3>ابقَ على تواصل</h3><a href={whatsappUrl('مرحباً ShineoraTech، أود مناقشة مشروعي.')} target="_blank" rel="noopener noreferrer">واتساب · <bdi dir="ltr">{site.phone}</bdi></a><a href={`mailto:${site.email}`}><bdi>{site.email}</bdi></a><LanguageSwitch language="ar" /></div></div><div className="footer-bottom"><span>© 2026 ShineoraTech. جميع الحقوق محفوظة.</span><span>صُمم بعناية، من أجلك.</span></div></div></footer>
    <a className="whatsapp-float" href={whatsappUrl('مرحباً ShineoraTech، أود مناقشة مشروعي الرقمي.')} target="_blank" rel="noopener noreferrer" aria-label="تواصل مع ShineoraTech على واتساب"><span>لنتحدث عن مشروعك</span></a>
  </>;
}
