'use client';
import { useRef, useState, type FormEvent, type CSSProperties } from 'react';
import { Globe2, ShoppingBag, PanelsTopLeft, PenTool, Sparkles, ShieldCheck, Check, Plus, MessageCircle, Smartphone, Gauge, HeartHandshake, ChevronLeft, ChevronRight } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { fr } from '@/content/fr';
import { WebsitePortfolio } from './website-portfolio';
import { site, whatsappUrl } from '@/lib/site';
import { Brand, ProductMockup, Reveal } from './landing';
const serviceLinks = [['/fr/creation-site-web/', 'Découvrir la création de sites web'], ['/fr/creation-site-ecommerce/', 'Découvrir les boutiques en ligne'], ['/fr/applications-web/', 'Découvrir les applications web']];
const serviceIcons = [Globe2, ShoppingBag, PanelsTopLeft, PenTool, Sparkles, ShieldCheck];
export function SectionTitle({ kicker, title, text }: {
    kicker: string;
    title: React.ReactNode;
    text?: string;
}) { return <div className="section-heading"><div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div>{text && <p className="section-intro">{text}</p>}</div>; }
export function Services() { return <section className="section light" id="services"><div className="container"><Reveal><SectionTitle kicker="01 / NOS EXPERTISES" title={<>Tout ce qu’il faut<br />pour aller plus loin.</>} text="Du premier site à l’outil métier sur mesure, nous créons le digital dont votre entreprise a besoin."/></Reveal><div className="services-grid">{fr.services.map((service, i) => { const Icon = serviceIcons[i]; return <Reveal key={service.title}><article className="service-card"><div className="service-top"><Icon size={25} strokeWidth={1.5}/><span>0{i + 1}</span></div><h3>{service.title}</h3><p>{service.text}</p>{serviceLinks[i] && <a className="text-link service-page-link" href={serviceLinks[i][0]}>{serviceLinks[i][1]} →</a>}<details><summary>En savoir plus <Plus size={16}/></summary><div className="service-detail">{service.detail}<a href="#contact">Parler de mon projet</a></div></details></article></Reveal>; })}</div><div className="services-note"><span>Vous avez déjà un site ? Donnez-lui une nouvelle dimension.</span><a href="#refonte">Découvrir la refonte</a></div></div></section>; }
export function ProjectCard({ project, index }: {
    project: typeof fr.projects[number];
    index: number;
}) { return <Reveal className="project-card"><article><div className={`project-stage stage-${project.kind}`}><span className="project-index">0{index + 1}</span><div className="stage-window"><ProductMockup kind={project.kind} compact/></div><span className="mockup-disclaimer">MAQUETTE ILLUSTRATIVE · DONNÉES FICTIVES</span></div><div className="project-copy"><p className="project-category">{project.category}</p><h3>{project.name}</h3><p className="project-headline">{project.headline}</p><details className="project-details"><summary>Voir le projet <Plus size={18}/></summary><div className="case-study"><h4>Le besoin</h4><p>{project.problem}</p><h4>La solution</h4><p>{project.solution}</p><ul>{project.features.map(f => <li key={f}><Check size={15}/>{f}</li>)}</ul>{project.tech.length > 0 && <><h4>Technologies sélectionnées</h4><div className="tech-tags">{project.tech.map(t => <span key={t}>{t}</span>)}</div></>}</div></details></div></article></Reveal>; }
export function Portfolio() { return <><section className="section portfolio" id="realisations"><div className="container"><Reveal><SectionTitle kicker="02 / RÉALISATIONS" title={<>Des sites à découvrir.<br /><span className="muted-title">Des univers singuliers.</span></>} text="Découvrez une sélection de sites web, puis explorez l’ensemble du portfolio."/></Reveal><WebsitePortfolio/></div></section><section className="section application-concepts" id="concepts-applications" aria-labelledby="concepts-title"><div className="container"><div className="concepts-heading"><p className="eyebrow">EXPLORATIONS / APPLICATIONS WEB</p><h2 id="concepts-title">Des concepts pour les usages métier.</h2><p className="section-intro">Recrutement et finance : trois interfaces illustratives pour explorer des parcours et des fonctionnalités.</p></div><div className="projects-grid">{fr.projects.map((p, i) => <ProjectCard key={p.name} project={p} index={i}/>)}</div><p className="portfolio-note">Ces interfaces sont des maquettes illustratives, sans données confidentielles.</p></div></section></>; }
export function WhyUs() { const benefits = [[PenTool, 'Une identité qui vous ressemble', 'Un design personnalisé, cohérent avec votre marque et vos clients.'], [Smartphone, 'À l’aise sur tous les écrans', 'Des parcours pensés pour le mobile, la tablette et l’ordinateur.'], [Gauge, 'La fluidité au quotidien', 'Des pages légères et des interactions utiles pour faciliter chaque visite.'], [ShieldCheck, 'Des bases solides', 'Des accès maîtrisés et un suivi technique adapté à votre solution.'], [HeartHandshake, 'Un partenaire, du début à la suite', 'Des échanges clairs, une prise en main et un support après livraison.']] as const; return <section className="section why" id="a-propos"><div className="container why-layout"><Reveal><p className="eyebrow">03 / L’ESPRIT SHINEORATECH</p><h2>Le digital est un outil.<br /><span className="accent">Votre réussite,<br />notre point de départ.</span></h2><p className="why-lead">ShineoraTech accompagne les entreprises et les entrepreneurs dans leurs projets digitaux : création de sites web, design d’interfaces et applications sur mesure. Notre approche commence par l’écoute de votre activité et de vos besoins, puis se poursuit du premier échange au lancement.</p><p className="audience">Pour les PME, commerces, salons de beauté, restaurants, écoles, professionnels, acteurs de l’immobilier et entrepreneurs au Maroc.</p><a href="#contact" className="text-link">Faisons connaissance</a></Reveal><div className="benefits">{benefits.map(([Icon, title, text]) => <div className="benefit" key={title}><span><Icon size={22} strokeWidth={1.5}/></span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>; }
export function Process() { const [active, setActive] = useState(0); return <section className="section light" id="processus"><div className="container"><SectionTitle kicker="04 / COMMENT ÇA SE PASSE" title={<>Une vision partagée.<br />Un chemin clair.</>} text="Vous savez où vous allez, ce qui se prépare et ce que nous construisons ensemble."/><div className="process-grid">{fr.process.map((p, i) => <button key={p.title} className={`process-step ${active === i ? 'active' : ''}`} aria-expanded={active === i} aria-controls="process-detail" onClick={() => setActive(i)}><span className="step-number">0{i + 1}</span><h3>{p.title}</h3><p>{p.text}</p><span className="step-progress"/></button>)}</div><div id="process-detail" className="process-detail" aria-live="polite"><div><span>ÉTAPE 0{active + 1}</span><p>{fr.process[active].detail}</p></div><div className="process-deliverable"><Check size={20}/>{fr.process[active].deliverable}</div></div></div></section>; }
function SalonPreview({ after = false }: {
    after?: boolean;
}) { return <div className={`salon-preview ${after ? 'salon-after' : 'salon-before'}`}><div className="salon-nav"><strong>{after ? 'ATELIER BEAUTÉ' : 'SALON DE BEAUTÉ'}</strong><span>{after ? 'Le salon  ·  Nos soins  ·  Contact' : 'Accueil | Services | Contact'}</span></div><div className="salon-content"><span>{after ? 'UN MOMENT POUR VOUS' : 'Bienvenue sur notre site'}</span><h3>{after ? <>Votre beauté.<br /><em>Naturellement.</em></> : 'Votre salon de beauté'}</h3><p>{after ? 'Des soins pensés pour vous, dans un cadre qui invite à ralentir.' : 'Nous proposons plusieurs prestations. Contactez-nous pour plus d’informations.'}</p><span className="salon-button">{after ? 'Réserver mon soin' : 'Contactez-nous'}</span></div><div className="salon-services"><span>{after ? '01  Visage' : 'Nos services'}</span><span>{after ? '02  Bien-être' : 'Soins visage'}</span><span>{after ? '03  Beauté' : 'Beauté et bien-être'}</span></div></div>; }
export function BeforeAfter() { const [value, setValue] = useState([50]); return <section className="section comparison-section" id="refonte"><div className="container"><SectionTitle kicker="05 / LE POUVOIR D’UNE REFONTE" title={<>Même activité.<br /><span className="accent">Tout change au premier regard.</span></>} text="Une présentation plus claire. Une identité plus forte. Un contact plus simple. Faites glisser pour comparer."/><div className="comparison" style={{ '--split': `${value[0]}%` } as CSSProperties}><div className="comparison-base"><SalonPreview after/></div><div className="comparison-overlay" style={{ clipPath: `inset(0 ${100 - value[0]}% 0 0)` }}><SalonPreview /></div><div className="comparison-labels"><span>Avant</span><span>Après ShineoraTech</span></div><div className="comparison-divider" style={{ left: `${value[0]}%` }} aria-hidden="true"><span><ChevronLeft size={16}/><ChevronRight size={16}/></span></div><Slider ref={node => { node?.querySelector('[role="slider"]')?.setAttribute('aria-label', 'Comparer le site avant et après la refonte'); }} className="comparison-slider" aria-label="Comparer le site avant et après la refonte" value={value} onValueChange={setValue} min={0} max={100} step={1}/></div><div className="comparison-caption"><span>Démonstration fictive : salon de beauté. Aucun résultat client n’est revendiqué.</span><span>Glissez le curseur · ou utilisez les touches directionnelles</span></div></div></section>; }
export function CTA() { return <section className="cta-band"><div className="container cta-inner"><div><p className="eyebrow">LE PROCHAIN PROJET, C’EST LE VÔTRE.</p><h2>Une idée en tête ?<br />Donnons-lui vie.</h2></div><div><p>Parlons-en et transformons votre idée en une solution digitale professionnelle.</p><div className="cta-actions"><a className="button ink-button" href="#contact">Demander un devis</a><a className="button outline-ink" href={whatsappUrl()} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>Discuter sur WhatsApp</a></div></div></div></section>; }
export function Contact() {
    const [type, setType] = useState('');
    const [budget, setBudget] = useState('');
    const [errors, setErrors] = useState<Record<string, string>>({});
    const [prepared, setPrepared] = useState('');
    const formRef = useRef<HTMLFormElement>(null);
    function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const value = (key: string) => String(data.get(key) || '').trim(); const err: Record<string, string> = {}; if (value('name').length < 2)
        err.name = 'Indiquez votre nom (au moins 2 caractères).'; const digits = value('phone').replace(/\D/g, ''); if (digits.length < 9 || digits.length > 15)
        err.phone = 'Indiquez un numéro valide avec son indicatif.'; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value('email')))
        err.email = 'Indiquez une adresse email valide.'; if (!type)
        err.type = 'Choisissez un type de projet.'; if (!budget)
        err.budget = 'Choisissez une fourchette de budget.'; if (value('message').length < 10)
        err.message = 'Décrivez votre projet en au moins 10 caractères.'; setErrors(err); if (Object.keys(err).length) {
        setPrepared('');
        requestAnimationFrame(() => formRef.current?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus());
        return;
    } const message = `Bonjour ShineoraTech 👋\nJe souhaite discuter de mon projet digital.\n\nNom : ${value('name')}\nEntreprise : ${value('company') || 'Non renseignée'}\nTéléphone : ${value('phone')}\nEmail : ${value('email')}\nProjet : ${type}\nBudget : ${budget}\n\n${value('message')}`; setPrepared(whatsappUrl(message)); }
    function field(name: string, label: string, kind = 'text', required = true, placeholder = '') { return <div className="form-field"><label htmlFor={name}>{label}{required && ' *'}</label><input id={name} name={name} type={kind} required={required} maxLength={name === 'name' || name === 'company' ? 100 : 160} placeholder={placeholder} autoComplete={name === 'name' ? 'name' : name === 'company' ? 'organization' : name === 'phone' ? 'tel' : 'email'} aria-invalid={!!errors[name]} aria-describedby={errors[name] ? `${name}-error` : undefined}/>{errors[name] && <span className="field-error" id={`${name}-error`}>{errors[name]}</span>}</div>; }
    return <section className="section contact" id="contact"><div className="container contact-layout"><div><p className="eyebrow">06 / PARLONS DE VOTRE PROJET</p><h2>Votre prochaine étape<br /><span className="accent">commence ici.</span></h2><p className="contact-intro">Une idée précise ou une première envie ? Racontez-nous. Nous vous aiderons à définir la bonne solution.</p><a className="contact-whatsapp" href={whatsappUrl()} target="_blank" rel="noopener noreferrer"><span><MessageCircle size={26}/></span><div><small>Vous préférez en discuter directement ?</small><strong>Écrivez-nous sur WhatsApp</strong><span>{site.phone}</span></div></a>{site.email && <a className="contact-email" href={`mailto:${site.email}`}><span>Par email</span><strong>{site.email}</strong></a>}<div className="contact-points"><p><Check size={16}/>Premier échange sans engagement</p><p><Check size={16}/>Une proposition adaptée à votre besoin</p><p><Check size={16}/>Accompagnement à chaque étape</p></div></div><form ref={formRef} onSubmit={submit} noValidate onChange={() => { if (prepared)
        setPrepared(''); }}><div className="form-top"><span>Décrivez-nous votre projet</span><small>* Champs obligatoires</small></div><div className="form-grid">{field('name', 'Nom', 'text', true, 'Votre nom')}{field('company', 'Entreprise', 'text', false, 'Nom de votre entreprise')}{field('phone', 'Téléphone / WhatsApp', 'tel', true, '+212 6…')}{field('email', 'Email', 'email', true, 'vous@entreprise.ma')}<div className="form-field"><label htmlFor="project-type">Type de projet *</label><Select value={type} onValueChange={v => { setType(v); setPrepared(''); }}><SelectTrigger id="project-type" aria-invalid={!!errors.type} aria-describedby={errors.type ? 'type-error' : undefined}><SelectValue placeholder="Sélectionner un projet"/></SelectTrigger><SelectContent>{fr.projectTypes.map(t => <SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select>{errors.type && <span id="type-error" className="field-error">{errors.type}</span>}</div><div className="form-field"><label htmlFor="budget">Budget envisagé *</label><Select value={budget} onValueChange={v => { setBudget(v); setPrepared(''); }}><SelectTrigger id="budget" aria-invalid={!!errors.budget} aria-describedby={errors.budget ? 'budget-error' : undefined}><SelectValue placeholder="Sélectionner un budget"/></SelectTrigger><SelectContent>{fr.budgets.map(t => <SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select>{errors.budget && <span id="budget-error" className="field-error">{errors.budget}</span>}</div><div className="form-field full"><label htmlFor="message">Votre message *</label><textarea name="message" id="message" required minLength={10} maxLength={1500} rows={4} placeholder="Votre activité, votre idée, ce que vous aimeriez améliorer…" aria-invalid={!!errors.message} aria-describedby={errors.message ? 'message-error' : undefined}/>{errors.message && <span id="message-error" className="field-error">{errors.message}</span>}</div></div><p className="form-notice">Votre demande sera préparée pour WhatsApp. Vous pourrez la relire et confirmer son envoi avant de nous la transmettre.</p><button type="submit" className="button form-submit">Envoyer ma demande <MessageCircle size={17}/></button>{Object.keys(errors).length > 0 && <p role="alert" className="form-error">Vérifiez les champs indiqués avant de continuer.</p>}{prepared && <div className="form-success" role="status"><Check size={21}/><div><strong>Votre demande est prête.</strong><p>Elle n’a pas encore été envoyée. Ouvrez WhatsApp puis confirmez l’envoi du message.</p><a href={prepared} className="button" target="_blank" rel="noopener noreferrer">Continuer sur WhatsApp</a></div></div>}<p className="privacy-note">Vos informations servent uniquement à traiter votre demande. Elles ne sont transmises à WhatsApp que lorsque vous choisissez de continuer. Aucun enregistrement dans ce formulaire.</p></form></div></section>;
}
export function Footer() { return <footer className="footer"><div className="container"><div className="footer-grid"><div><a href="#accueil" aria-label="Retour à l’accueil"><Brand /></a><p>Votre vision. Notre technologie.</p><span className="footer-location">Une agence digitale, tournée vers vos ambitions.</span></div><div><h3>Explorer</h3><a href="#services">Services</a><a href="#realisations">Réalisations</a><a href="#a-propos">À propos</a><a href="#contact">Contact</a></div><div><h3>Restons en contact</h3><a href={whatsappUrl()} target="_blank" rel="noopener noreferrer">WhatsApp · {site.phone}</a>{site.email && <a href={`mailto:${site.email}`}>{site.email}</a>}<p>Maroc · Projets à distance</p></div>{site.socials.length > 0 && <div><h3>Nos réseaux</h3>{site.socials.map(s => <a key={s.name} href={s.url} target="_blank" rel="noopener noreferrer">{s.name}</a>)}</div>}</div><div className="footer-bottom"><span>© 2026 ShineoraTech. Tous droits réservés.</span><span>Conçu avec soin. Pensé pour vous.</span></div></div></footer>; }
export function WhatsAppButton() { return <a className="whatsapp-float" href={whatsappUrl()} target="_blank" rel="noopener noreferrer" aria-label="Discuter avec ShineoraTech sur WhatsApp"><MessageCircle size={23}/><span>Parlons de votre projet</span></a>; }
